site_name: LambentLight for FiveM and RedM

nav:
  - LambentLight: index.md
  - Getting started: getting-started.md
  - Resource Manager: resources.md
  - MySQL Database: mysql.md
  - Web API:
    - About: api/about.md
    - Authentication: api/authentication.md
    - Objects: api/objects.md
    - Endpoints - Basics: api/e_basics.md
    - Endpoints - Builds: api/e_builds.md
    - Endpoints - Data Folders: api/e_datafolders.md
    - Endpoints - Runtime: api/e_runtime.md
  - Development:
    - Development Tools: development/tools.md
    - Metadata Repos: development/metadata.md
  - Software License: license.md

repo_name: LambentLight/LambentLight
repo_url: https://github.com/LambentLight/LambentLight

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details

theme:
  feature:
    tabs: true
  name: material
  palette:
    primary: cyan
    accent: cyan

extra:
  social:
    - type: discord
      link: https://discord.gg/Cf6sspj
    - type: github
      link: https://github.com/justalemon
    - type: steam
      link: https://steamcommunity.com/profiles/76561198118215221/
    - type: twitter
      link: https://twitter.com/justlemonades
    - type: twitch
      link: https://www.twitch.tv/justlemoncl
    - type: gamepad
      link: https://www.gta5-mods.com/users/justalemon
